### ISSUE TITLE
`setTimeout` callback doesn't seem 100 % reliable

### ISSUE THREAD

**Issue by SantosGuillamot** [luisherranz/block-hydration-experiments#69] opened 2022-09-16 07:13 UTC
As discussed [here](https://github.com/WordPress/block-hydration-experiments/pull/63#issuecomment-1246463895), it looks like the [setTimeout callback](https://github.com/WordPress/block-hydration-experiments/blob/dynamic-blocks/src/gutenberg-packages/hydration.js#L128) we are using inside `connectedCallback` is not 100% reliable. It seems to be running before the HTML parsing has finished. Here you have one example of when this is a problem:

<a href="https://www.loom.com/share/08bf09f4a6434c3791d5d719fb5a2eb0">
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/08bf09f4a6434c3791d5d719fb5a2eb0-with-play.gif">
</a>

It seems that if the page is loaded quickly, the state defined in PHP and sent as an attribute is undefined in the view.js files. These are the two examples I'm talking about: [Title](https://github.com/WordPress/block-hydration-experiments/blob/dynamic-blocks/src/blocks/dynamic-interactive-parent/view.js#L18) & [Date](https://github.com/WordPress/block-hydration-experiments/blob/dynamic-blocks/src/blocks/dynamic-interactive-child/view.js#L8).

As Luis shared [here](https://github.com/WordPress/block-hydration-experiments/pull/63#issuecomment-1247844599), Jake Archibald talks about this problem in [this video](https://youtu.be/_iq1fPjeqMQ?t=929). He proposes:

* A weird custom element hack that can inform the parent when it's rendered, because at that moment, all the children should be rendered as well:

```html
<wp-block>
  <!-- children is processed first -->
  children...
  <!-- then this final element is processed -->
  <children-finished-processing></children-finished-processing>
</wp-block>
````
* Use mutation observers.

**Comment by luisherranz** [comment] 2022-10-10 07:55
@senadir and I have been looking more deeply into this, and there doesn't seem to be a way to solve this using the mutation observer alone. So unless there's a new idea, we would need to go with the element hack described above. 

@senadir suggested that instead of a custom element, we could use a combination of a CSS-neutral element (like `template`, `script`, `style`...) to avoid messing with the CSS, and a mutation observer to detect when it appears in the DOM.

**Comment by senadir** [comment] 2022-10-10 23:06
HTML comments are picked up by `MutationObserver` and have no drawbacks. We do run the risk of optimization plugins removing comments before page render https://wordpress.org/support/topic/strip-html-comments-is-it-safe/

In my testing, it seems that `MutationObserver` does indeed pick up a template tag 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/6165348/194934499-a0ea310b-057f-4361-80cb-5fd70dc6d903.png">

**Comment by senadir** [comment] 2022-10-10 23:13
While `setTimeout` isn't ideal because it just defers the work to the next possible task, you can possibly try using `requestIdleCallback` which should defer to when the browser is idle, this means when the browser is done parsing data.

**Comment by tomalec** [comment] 2022-11-04 20:56
> it looks like the [setTimeout callback](https://github.com/WordPress/block-hydration-experiments/blob/dynamic-blocks/src/gutenberg-packages/hydration.js?rgh-link-date=2022-09-16T07%3A13%3A41Z#L128) we are using inside connectedCallback is not 100% reliable

I'd be happy to know the rationale behind the `setTimoeut` implementation. What was the goal there?

First of all using `connectedCallback` there is no guarantee that the element is actually connected :) 
See the note at https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements#using_the_lifecycle_callbacks
> Note: connectedCallback may be called once your element is no longer connected, use [Node.isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected) to make sure.

Also, from a custom element life-cycle perspective, `connectedCallback` is also not the right moment to collect attribute values - that should be done in `attributeChangedCallback`.

`connectedCallback` is there to be called when the element itself was connected, and has nothing to do with it's children.

**Comment by luisherranz** [comment] 2022-11-05 12:11
> I'd be happy to know the rationale behind the setTimoeut implementation. What was the goal there?

We need a callback that triggers once the custom element's children have been created because they are required for the hydration (to extract sourced attribute, use `hydrate` instead of `render`, etc.).

**Comment by tomalec** [comment] 2022-11-05 14:56
> We need a callback that triggers once the custom element's children have been created because they are required for the hydration (to extract sourced attribute, use `hydrate` instead of `render`, etc.).

Given this is an element in the live document. So in DOM "Have been created" is not an event that happens only once, but may happen later in runtime. New children elements could be added, and old ones could be removed.


So to be precise on what we need, I guess "created" is also not the thing we need, as children may be created far **before** or `wp-block` is created. I guess we need the moment when they are connected to `wp-block` subtree.

When you write "sourced attribute" what do you mean by "sourced" and that's the attribute of what?


Please correct me if I'm wrong here because it's all based on suspicions ;) And I don't know the lingo you use in this project, but rather stick to HTML definitions. What we need here is that:

Run a piece of code:
1. Only once
2. only after initial parsing of the document (/subtree/`.innerHTML`)
3. only after the parser reaches the end of our element/subtree/document fragment
4. ignore all the subsequent changes/mutations to that subtree

------


So if the above is what we want, for sure `conectedCallback() { setTimeout` has no chance to be reliable.

----
If we really want to achieve "parser reaches the end of our element" then the problem is HTML parser does expose any callback for parsing the end tag. AFAIR this is due to how the HTML parser is implemented deep in browser engines.

The only element that somewhat has that feature is the `<template>` element.

That is precisely the reason why [Declarative Shadow DOM](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Declarative-Shadow-DOM.md) eventually ended up being specified & implemented as [`<template shadowroot>`](https://web.dev/declarative-shadow-dom/).

BTW, DSD was created among others to support Server Side Rendering. So I think it's worth looking for inspiration, especially since most of the points  I mentioned above, were also discussed and covered there.

**Comment by tomalec** [comment] 2022-11-05 14:57
Also, as I usually like to step back from the solution, to define a problem, and find a new out without a bias of having one in mind:

Do we really need to do it "once the custom element's children have been created"? If so, why? Maybe we can hydrate the elements as they come?

**Comment by luisherranz** [comment] 2022-11-14 10:48
> When you write "sourced attribute" what do you mean by "sourced" and that's the attribute of what?

Sourcing attributes is a common way to store block attributes in the HTML to avoid duplication of data and sync issues: [documentation](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-attributes/).

> Do we really need to do it "once the custom element's children have been created"? If so, why?

Yes. Before we can hydrate the block, we need to get the sourced attributes, whose values are stored somewhere in the children instead of the JSON (block comment) and we also need all the children already created to be able to call React/Preact's `hydrate` function and avoid the unnecessary recreation of DOM nodes: [documentation](https://preactjs.com/guide/v10/api-reference/).

---

By the way, this issue is only relevant if we finally use a custom element to do the hydration, which is still not clear. Let's continue that conversation on [this issue](https://github.com/WordPress/block-hydration-experiments/issues/49) instead.

**Comment by luisherranz** [comment] 2023-01-16 16:33
Closed as we're not actively working on this experiment anymore.

**Closed as not planned by luisherranz** 2023-01-16 16:33 UTC
Labels: bug, 🧩 Custom Elements Hydration
